/**
 * Vision bypass tool: lets text-only host models read images through the
 * Antigravity pool (a Gemini model describes the image in text).
 */
import { readdir, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve as resolvePath } from "node:path";
import { dshHomePath } from "@deepseek-ai/dsh-home-paths";

const MAX_INPUT_IMAGE_BYTES = 10 * 1024 * 1024;

// Host placeholders carry "sha256:<hex>"; 8 hex chars are enough to disambiguate
// objects while staying copyable from the placeholder text.
const ATTACHMENT_HASH_RE = /^(?:sha256:)?([a-fA-F0-9]{8,64})$/;
const DATA_URL_RE = /^data:([^;,]+);base64,(.*)$/s;

const EXTENSION_MEDIA_TYPES = {
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".gif": "image/gif",
};

const DEFAULT_VISION_PROMPT =
  "Describe this image in detail, including any visible text, layout, and notable elements.";

function mediaTypeForFilename(name) {
  const dot = name.lastIndexOf(".");
  if (dot === -1) return "image/png";
  return EXTENSION_MEDIA_TYPES[name.slice(dot).toLowerCase()] || "image/png";
}

function assertSizeLimit(base64) {
  const byteLength = Buffer.byteLength(base64, "base64");
  if (byteLength > MAX_INPUT_IMAGE_BYTES) {
    throw new Error(`image exceeds size limit: ${byteLength} bytes > ${MAX_INPUT_IMAGE_BYTES} bytes`);
  }
}

/**
 * Resolve the tool's `image` argument to { base64, mimeType }.
 * Accepts, in order: an attachment hash prefix (looked up under
 * attachmentsRoot, the DSH attachments object store), a data: URL, or a
 * local file path. http(s) URLs are rejected outright (SSRF surface).
 */
export async function resolveImageInput(imageRef, { attachmentsRoot = dshHomePath("attachments", "v1", "objects") } = {}) {
  const ref = typeof imageRef === "string" ? imageRef.trim() : "";
  if (!ref) {
    throw new Error("image must be an attachment hash prefix, a local file path, or a data: URL.");
  }
  if (/^https?:\/\//i.test(ref)) {
    // ponytail: if URL support is ever added, the first new test must refuse
    // localhost/intranet targets — that rejection is the SSRF boundary.
    throw new Error("http(s) URLs are not supported; save the image locally or attach it in chat.");
  }

  const hashMatch = ATTACHMENT_HASH_RE.exec(ref);
  if (hashMatch) {
    const hex = hashMatch[1].toLowerCase();
    const bucket = resolvePath(attachmentsRoot, hex.slice(0, 2));
    const entries = existsSync(bucket)
      ? (await readdir(bucket)).filter((name) => name.toLowerCase().startsWith(hex))
      : [];
    if (entries.length === 0) {
      throw new Error(`No attachment found for hash prefix "${ref}" under ${attachmentsRoot}.`);
    }
    if (entries.length > 1) {
      throw new Error(
        `Attachment hash prefix "${ref}" is ambiguous: ${entries.length} objects share it. Use a longer prefix.`,
      );
    }
    const bytes = await readFile(resolvePath(bucket, entries[0]));
    const base64 = bytes.toString("base64");
    assertSizeLimit(base64);
    return { base64, mimeType: mediaTypeForFilename(entries[0]) };
  }

  if (ref.startsWith("data:")) {
    const match = DATA_URL_RE.exec(ref);
    if (!match) {
      throw new Error('Invalid data: URL (expected "data:<mime>;base64,<payload>").');
    }
    assertSizeLimit(match[2]);
    return { base64: match[2], mimeType: match[1] };
  }

  const filePath = resolvePath(ref);
  if (!existsSync(filePath)) {
    throw new Error(`Image file not found: ${filePath}`);
  }
  const bytes = await readFile(filePath);
  const base64 = bytes.toString("base64");
  assertSizeLimit(base64);
  return { base64, mimeType: mediaTypeForFilename(filePath) };
}

export function createVisionTool(poolManager, sendVisionRequestFn) {
  return {
    name: "antigravity_read_image",
    description:
      "Read an image and return a detailed text description generated by Gemini from the Antigravity pool, for models that cannot see images. " +
      "When you see a placeholder like [image omitted because this model accepts text only; attachment sha256:<hex>], extract the hex after " +
      "'sha256:' and pass it as the image argument. " +
      "Do not use this tool when the current model accepts image input itself. " +
      "Only accepts an attachment hash prefix, a local file path, or a data: URL; http(s) URLs are not supported.",
    parameters: {
      type: "object",
      properties: {
        image: {
          type: "string",
          description:
            "attachment hash prefix (the hex after 'sha256:' in the image placeholder), a local file path, or a data: URL",
        },
        prompt: {
          type: "string",
          description: "What to look for or answer about the image. Defaults to a full description.",
        },
      },
      required: ["image"],
    },
    output: {
      schema: {
        type: "object",
        properties: {
          description: { type: "string" },
          image: { type: "string" },
          account: { type: "string" },
        },
      },
      // The host calls render(exec.arguments, value): the execute result is
      // the second argument.
      render: (args, value) => [
        {
          type: "text",
          text: `Image description (via ${value.account}):\n\n${value.description}`,
        },
      ],
    },
    execute: async (args) => {
      const imageRef = String(args.image || "").trim();
      if (!imageRef) {
        throw new Error("image must be an attachment hash prefix, a local file path, or a data: URL.");
      }
      const { base64, mimeType } = await resolveImageInput(imageRef);
      const result = await sendVisionRequestFn(base64, mimeType, args.prompt || DEFAULT_VISION_PROMPT);
      if (!result?.text) {
        throw new Error(result?.error || "Failed to describe the image through the Antigravity pool.");
      }
      return { description: result.text, image: args.image, account: result.accountEmail };
    },
  };
}
